class PluginModel{
  String PluginName;
  String like;
  String popularity;
  String url;
  PluginModel(this.PluginName,this.url,this.like,this.popularity);
}

List<PluginModel> allPlugin =[
  PluginModel("image_picker","https://pub.dev/packages/image_picker" , "Likes : 4871" , "Popularity : 100%" ),
  PluginModel("get","https://pub.dev/packages/get" , "Likes : 11339" , "Popularity : 100%" ),
  PluginModel("fluttertoast","https://pub.dev/packages/fluttertoast" , "Likes : 2554" , "Popularity : 100%" ),
  PluginModel("flutter_screenutil","https://pub.dev/packages/flutter_screenutil" , "Likes : 2836" , "Popularity : 100%"),
  PluginModel("permission_handler","https://pub.dev/packages/permission_handler" , "Likes : 3417" , "Popularity : 100%"),
  PluginModel("intl","https://pub.dev/packages/intl" , "Likes : 3730" , "Popularity : 100%"),
  PluginModel("syncfusion_flutter_datepicker","https://pub.dev/packages/syncfusion_flutter_datepicker" , "Likes : 1016" , "Popularity : 99%"),
  PluginModel("shared_preferences","https://pub.dev/packages/shared_preferences" , "Likes : 6774" , "Popularity : 100%"),
  PluginModel("delayed_display","https://pub.dev/packages/delayed_display" , "Likes : 374" , "Popularity : 96%"),
  PluginModel("url_launcher","https://pub.dev/packages/url_launcher" , "Likes : 5465" , "Popularity : 100%"),
  PluginModel("http","https://pub.dev/packages/http" , "Likes : 5747" , "Popularity : 100%"),
  PluginModel("flutter_svg","https://pub.dev/packages/flutter_svg" , "Likes : 3498" , "Popularity : 100%"),
  PluginModel("google_fonts","https://pub.dev/packages/google_fonts" , "Likes : 4293" , "Popularity : 100%"),
  PluginModel("lottie","https://pub.dev/packages/lottie" , "Likes : 2519" , "Popularity : 100%"),
  PluginModel("audioplayers","https://pub.dev/packages/audioplayers" , "Likes : 1936" , "Popularity : 100%"),
  PluginModel("simple_cookies","https://pub.dev/packages/simple_cookies" , "Likes : 9" , "Popularity : 82%"),
  PluginModel("flutter_facebook_auth","https://pub.dev/packages/flutter_facebook_auth" , "Likes : 986" , "Popularity : 100%"),
  PluginModel("google_sign_in","https://pub.dev/packages/google_sign_in" , "Likes : 2112" , "Popularity : 100%"),
  PluginModel("widget_with_codeview","https://pub.dev/packages/widget_with_codeview" , "Likes : 49" , "Popularity : 86%"),
  PluginModel("flutter_native_splash","https://pub.dev/packages/flutter_native_splash" , "Likes : 5144" , "Popularity : 100%"),
  PluginModel("flare_splash_screen","https://pub.dev/packages/flare_splash_screen" , "Likes : 217" , "Popularity : 94%"),
  PluginModel("flutter_launcher_icons","https://pub.dev/packages/flutter_launcher_icons" , "Likes : 4926" , "Popularity : 100%"),
  PluginModel("firebase_core","https://pub.dev/packages/firebase_core" , "Likes : 2428" , "Popularity : 100%"),
  PluginModel("firebase_database","https://pub.dev/packages/firebase_database" , "Likes : 480" , "Popularity : 99%"),
  PluginModel("firebase_storage","https://pub.dev/packages/firebase_storage" , "Likes : 1143" , "Popularity : 100%"),
  PluginModel("cloud_firestore","https://pub.dev/packages/cloud_firestore" ,"Likes : 2663" , "Popularity : 100%"),
  PluginModel("sign_in_with_apple","https://pub.dev/packages/sign_in_with_apple" ,"Likes : 1249" , "Popularity : 100%"),
  PluginModel("flutter_appauth","https://pub.dev/packages/flutter_appauth" ,"Likes : 235" , "Popularity : 98%"),
  PluginModel("sign_button","https://pub.dev/packages/sign_button" ,"Likes : 141" , "Popularity : 93%"),
  PluginModel("email_auth","https://pub.dev/packages/email_auth" ,"Likes : 135" , "Popularity : 96%"),
  PluginModel("twitter_login","https://pub.dev/packages/twitter_login" ,"Likes : 85" , "Popularity : 97%"),
  PluginModel("firebase_auth","https://pub.dev/packages/firebase_auth" ,"Likes : 2935" , "Popularity : 100%"),
  PluginModel("local_auth","https://pub.dev/packages/local_auth" ,"Likes : 1840" , "Popularity : 100%"),
  PluginModel("biometric_storage","https://pub.dev/packages/biometric_storage" ,"Likes : 173" , "Popularity : 93%"),
  PluginModel("flutter_app_lock","https://pub.dev/packages/flutter_app_lock" ,"Likes : 81" , "Popularity : 93%"),
  PluginModel("pattern_lock","https://pub.dev/packages/pattern_lock" ,"Likes : 25" , "Popularity : 87%"),
  PluginModel("pin_code_fields","https://pub.dev/packages/pin_code_fields" ,"Likes : 1655" , "Popularity : 100%"),
  PluginModel("pin_code_text_field","https://pub.dev/packages/pin_code_text_field" ,"Likes : 133" , "Popularity : 98%"),
  PluginModel("pinput","https://pub.dev/packages/pinput" ,"Likes : 1392" , "Popularity : 99%"),
  PluginModel("otp_text_field","https://pub.dev/packages/otp_text_field" ,"Likes : 163" , "Popularity : 99%"),
  PluginModel("in_app_review","https://pub.dev/packages/in_app_review" ,"Likes : 1219" , "Popularity : 99%"),
  PluginModel("rate_my_app","https://pub.dev/packages/rate_my_app" ,"Likes : 468" , "Popularity : 98%"),
  PluginModel("reviews_slider","https://pub.dev/packages/reviews_slider" ,"Likes : 89" , "Popularity : 84%"),
  PluginModel("sqflite","https://pub.dev/packages/sqflite" ,"Likes : 3596" , "Popularity : 100%"),
  PluginModel("sqflite_common_ffi","https://pub.dev/packages/sqflite_common_ffi" ,"Likes : 165" , "Popularity : 97%"),
  PluginModel("flutter_secure_storage","https://pub.dev/packages/flutter_secure_storage" ,"Likes : 2505" , "Popularity : 100%"),
  PluginModel("get_storage","https://pub.dev/packages/get_storage" ,"Likes : 1167" , "Popularity : 99%"),
  PluginModel("home_widget","https://pub.dev/packages/home_widget" ,"Likes : 721" , "Popularity : 95%"),
  PluginModel("change_app_package_name","https://pub.dev/packages/change_app_package_name" ,"Likes : 917" , "Popularity : 99%"),
  PluginModel("external_app_launcher","https://pub.dev/packages/external_app_launcher" ,"Likes : 171" , "Popularity : 97%"),
  PluginModel("flutter_dynamic_icon","https://pub.dev/packages/flutter_dynamic_icon" ,"Likes : 188" , "Popularity : 92%"),
  PluginModel("variable_app_icon","https://pub.dev/packages/variable_app_icon" ,"Likes : 44" , "Popularity : 77%"),
  PluginModel("introduction_screen","https://pub.dev/packages/introduction_screen" ,"Likes : 2011" , "Popularity : 99%"),
  PluginModel("intro_slider","https://pub.dev/packages/intro_slider" ,"Likes : 971" , "Popularity : 98%"),
  PluginModel("flutter_onboard","https://pub.dev/packages/flutter_onboard" ,"Likes : 131" , "Popularity : 92%"),
  PluginModel("onboarding_overlay","https://pub.dev/packages/onboarding_overlay" ,"Likes : 212" , "Popularity : 86%"),
  PluginModel("flutter_onboarding_slider","https://pub.dev/packages/flutter_onboarding_slider" ,"Likes : 113" , "Popularity : 91%"),
  PluginModel("onboarding","https://pub.dev/packages/onboarding" ,"Likes : 123" , "Popularity : 94%"),
  PluginModel("onboarding_animation","https://pub.dev/packages/onboarding_animation" ,"Likes : 49" , "Popularity : 82%"),
  PluginModel("flutter_swiper_null_safety","https://pub.dev/packages/flutter_swiper_null_safety" ,"Likes : 85" , "Popularity : 98%"),
  PluginModel("table_calendar","https://pub.dev/packages/table_calendar" ,"Likes : 2002" , "Popularity : 99%"),
  PluginModel("syncfusion_flutter_calendar","https://pub.dev/packages/syncfusion_flutter_calendar" ,"Likes : 991" , "Popularity : 99%"),


];